name: Deploy to Plesk Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t my-nextjs-app .

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Plesk Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Stop existing container if exists
          ssh $SSH_USER@$SSH_HOST "docker stop my-nextjs-app || true"
          ssh $SSH_USER@$SSH_HOST "docker rm my-nextjs-app || true"

          # Remove old image
          ssh $SSH_USER@$SSH_HOST "docker rmi my-nextjs-app || true"

          # Copy and load new image
          docker save my-nextjs-app | ssh $SSH_USER@$SSH_HOST "docker load"

          # Run new container
          ssh $SSH_USER@$SSH_HOST "docker run -d \
            --name my-nextjs-app \
            -p 3000:3000 \
            -e NODE_ENV=production \
            my-nextjs-app"
